/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ArmazenamentoRouteImport } from './routes/armazenamento'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ApiPublicMediaProxyRouteImport } from './routes/api/public/media-proxy'
import { Route as ApiPublicHooksPublishDueRouteImport } from './routes/api/public/hooks/publish-due'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmazenamentoRoute = ArmazenamentoRouteImport.update({
  id: '/armazenamento',
  path: '/armazenamento',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaProxyRoute = ApiPublicMediaProxyRouteImport.update({
  id: '/api/public/media-proxy',
  path: '/api/public/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPublishDueRoute =
  ApiPublicHooksPublishDueRouteImport.update({
    id: '/api/public/hooks/publish-due',
    path: '/api/public/hooks/publish-due',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/vendas': typeof VendasRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/vendas': typeof VendasRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/vendas': typeof VendasRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/armazenamento'
    | '/vendas'
    | '/api/public/media-proxy'
    | '/api/public/hooks/publish-due'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/armazenamento'
    | '/vendas'
    | '/api/public/media-proxy'
    | '/api/public/hooks/publish-due'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/armazenamento'
    | '/vendas'
    | '/api/public/media-proxy'
    | '/api/public/hooks/publish-due'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ArmazenamentoRoute: typeof ArmazenamentoRoute
  VendasRoute: typeof VendasRoute
  ApiPublicMediaProxyRoute: typeof ApiPublicMediaProxyRoute
  ApiPublicHooksPublishDueRoute: typeof ApiPublicHooksPublishDueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armazenamento': {
      id: '/armazenamento'
      path: '/armazenamento'
      fullPath: '/armazenamento'
      preLoaderRoute: typeof ArmazenamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-proxy': {
      id: '/api/public/media-proxy'
      path: '/api/public/media-proxy'
      fullPath: '/api/public/media-proxy'
      preLoaderRoute: typeof ApiPublicMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-due': {
      id: '/api/public/hooks/publish-due'
      path: '/api/public/hooks/publish-due'
      fullPath: '/api/public/hooks/publish-due'
      preLoaderRoute: typeof ApiPublicHooksPublishDueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ArmazenamentoRoute: ArmazenamentoRoute,
  VendasRoute: VendasRoute,
  ApiPublicMediaProxyRoute: ApiPublicMediaProxyRoute,
  ApiPublicHooksPublishDueRoute: ApiPublicHooksPublishDueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
